[[CURRENCIES]]
code="LOH"
issuer="r95GJxcghgMyQXittPHjYZvGUMWfVwtzPs"
display_decimals=6
name="Lee One Hour"
desc="대한민국 제21대 이재명 대통령의 한시간은 대한민국 국민 51,169,148명의 시간입니다. L이재명 O원 H아워 - Every moment, always forever. 디지털 헤리티지 아카이빙 프로젝트 The LJM Clockwork의 네이티브 유틸리티 토큰입니다."
image="https://yesoklab.github.io/loh-website/loh_coin_image.png"
conditions="이 토큰은 이재명 대통령의 시간 철학을 기념하고 The LJM Clockwork 생태계에서 거버넌스, 스테이킹, 접근권한, 수수료 등의 유틸리티 기능을 제공합니다."

# Additional metadata for enhanced compatibility
[CURRENCIES.properties]
total_supply="51169148"
symbol="LOH"
website="https://yesoklab.github.io/loh-website/"
whitepaper="https://yesoklab.github.io/loh-website/"
social_twitter="https://x.com/YesOkLab"
social_telegram="t.me/YesOkLab_NFT"
company="YesOkLab"
company_website="www.ljmsider.com"
